default:
  dora_dir: /cs/labs/adiyoss/yair.shemer/encodec-experiments
  partitions:
    global: debug
    team: debug
  reference_dir: /cs/labs/adiyoss/yair.shemer/encodec-experiments/ref
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: /cs/labs/adiyoss/yair.shemer/encodec-experiments
  partitions:
    global: debug
    team: debug
  reference_dir: /cs/labs/adiyoss/yair.shemer/encodec-experiments/ref
