# @package __global__

# WARNING: This is a base configuration file shared across ALL solvers in AudioCraft
# Please don't update this file directly. Instead use distinct configuration files
# to override the below configuration.
datasource:
  max_sample_rate: 44100
  max_channels: 2

  train: egs/debug/tr/data.jsonl
  valid: egs/debug/cv/data.jsonl
  evaluate: egs/debug/tt/data.jsonl
  generate: egs/debug/cv/data.jsonl
