# @package __global__

defaults:
  - compression/default
  - /model: encodec/complex/denoise
  - override /dset: audio/valentini_noisy_56spk
  - _self_

channels: 1
sample_rate: 16000

logging:
  level: INFO
  log_updates: 10
  log_wandb: true

wandb:
  with_media_logging: true
  project:  audiocraft-encodec
  name:  # optional name for the experiment
  group:  # optional group


# very small dataset
dataset:
  batch_size: 1
  num_workers: 10
  segment_duration: 1
  valid:
    num_samples: 10
  evaluate:
    num_samples: 10
  generate:
    num_samples: 2
    segment_duration: 2

# limited training
evaluate:
  every: 1
generate:
  every: 1
optim:
  epochs: 50
  updates_per_epoch: 10
